//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIX.Analyzers.Analyzers.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NIX.Analyzers.Rules.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines should be a readable, not too long..
        /// </summary>
        internal static string Nix01Description {
            get {
                return ResourceManager.GetString("Nix01Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line must be no longer than {0} characters (now {1})..
        /// </summary>
        internal static string Nix01MessageFormat {
            get {
                return ResourceManager.GetString("Nix01MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line is too long.
        /// </summary>
        internal static string Nix01Title {
            get {
                return ResourceManager.GetString("Nix01Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods should be a readable, not too long..
        /// </summary>
        internal static string Nix02Description {
            get {
                return ResourceManager.GetString("Nix02Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be no longer than {1} lines (now {2})..
        /// </summary>
        internal static string Nix02MessageFormat {
            get {
                return ResourceManager.GetString("Nix02MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method is too long.
        /// </summary>
        internal static string Nix02Title {
            get {
                return ResourceManager.GetString("Nix02Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too long.
        /// </summary>
        internal static string Nix03Description {
            get {
                return ResourceManager.GetString("Nix03Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; must be no longer than {1} lines (now {2})..
        /// </summary>
        internal static string Nix03MessageFormat {
            get {
                return ResourceManager.GetString("Nix03MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files should be a readable, not too long..
        /// </summary>
        internal static string Nix03Title {
            get {
                return ResourceManager.GetString("Nix03Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters quantity is exceeded. Reduce it.
        /// </summary>
        internal static string Nix04Description {
            get {
                return ResourceManager.GetString("Nix04Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} parameters in &quot;{1}&quot; method but the maximum allowed quantity is {2}..
        /// </summary>
        internal static string Nix04MessageFormat {
            get {
                return ResourceManager.GetString("Nix04MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many parameters in method.
        /// </summary>
        internal static string Nix04Title {
            get {
                return ResourceManager.GetString("Nix04Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters quantity is exceeded. Reduce it.
        /// </summary>
        internal static string Nix05Description {
            get {
                return ResourceManager.GetString("Nix05Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} parameters in &quot;{1}&quot; constructor but the maximum allowed quantity is {2}..
        /// </summary>
        internal static string Nix05MessageFormat {
            get {
                return ResourceManager.GetString("Nix05MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many parameters in constructor.
        /// </summary>
        internal static string Nix05Title {
            get {
                return ResourceManager.GetString("Nix05Title", resourceCulture);
            }
        }
    }
}
