name: Push

on:
  workflow_dispatch:

env:
  NUGET_PROJECT_PATH: nuget/NIX.Analyzers
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dotnet
        uses: actions/setup-dotnet@v1

      - name: Set Environment Variables
        uses: ./.github/actions/setvars
        with:
          varFilePath: ./.github/variables/versioning.env

      - name: Restore packages
        run: dotnet restore ${{ env.NUGET_PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.NUGET_PROJECT_PATH }}/NIX.Analyzers.csproj --no-restore

      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{ secrets.github_token }}
          prefix: ${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}

      - name: Pack project
        run: dotnet pack ${{ env.NUGET_PROJECT_PATH }}/NIX.Analyzers.csproj /p:PackageVersion=${{ env.MAJOR_VERSION }}.${{ env.MINOR_VERSION }}.$(($BUILD_NUMBER-1)) --no-restore --no-build --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Push package
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
