name: Push

on:
  workflow_dispatch:

env:
  NUGET_PROJECT_PATH: nuget/NIX.Analyzers
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

jobs:
  push:
    name: Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dotnet
        uses: actions/setup-dotnet@v1

      - name: Restore packages
        run: dotnet restore ${{ env.NUGET_PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.NUGET_PROJECT_PATH }}/NIX.Analyzers.csproj --no-restore

      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Set version
        id: version
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ steps.previoustag.outputs.tag }}
          find: 'v'
          replace: ''

      - name: Pack project
        run: dotnet pack ${{ env.NUGET_PROJECT_PATH }}/NIX.Analyzers.csproj /p:PackageVersion=${{ steps.version.outputs.value }} --no-restore --no-build --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Push package
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
